comment/urls.py
from __future__ import unicode_literals

from django.conf.urls import url
from comment.views import (comment_create,
                           comment_update,
                           comment_delete)

app_name = 'comment'

urlpatterns = [
    url(r'^create/$', comment_create, name='create'),
    url(r'^(?P<id>\d+)/update/$', comment_update, name='update'),
    url(r'^(?P<id>\d+)/delete/$', comment_delete, name='delete'),
]

webpage/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'social/', include('social.apps.django_app.urls', namespace='social')),

    url(r'^comment/', include('comment.urls', namespace='comment')),
    url(r'^', include('message.urls', namespace='message')),
    ]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comment/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.conf import settings
from django.utils.translation import ugettext_lazy as _


class CommentManager(models.Manager):
    def filter_by_instance(self, instance):
        content_type = ContentType.objects.get_for_model(instance.__class__)
        obj_id = instance.id
        qs = super(CommentManager, self).filter(content_type=content_type, object_id=obj_id, parent=None)
        return qs


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="comments", verbose_name=_("Автор коментаря"),
                             on_delete=models.CASCADE, default=1)
    # slug = models.SlugField(verbose_name=_("Ім`я коментаря транслітом"), blank='', unique=)
    text = models.TextField(verbose_name=_('Текст коментаря'), max_length=500)
    date = models.DateTimeField(auto_now_add=True, verbose_name=_("Дата створення"))
    update = models.DateTimeField(auto_now=True, verbose_name=_("Дата оновлення"))

    parent = models.ForeignKey('self', null=True, blank=True)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    objects = CommentManager()

    class Meta:
        ordering = ['-date', ]
        db_table = "comments"
        verbose_name = _("Коментар")
        verbose_name_plural = _("Коментарі")

    def __str__(self):
        return str(self.id)

    def children(self):
        instance = self
        return Comment.objects.filter(parent=instance)

    def has_parent_children(self):
        instance = self
        return hasattr(instance.parent, 'children')

comment/forms.py
from __future__ import unicode_literals

from django import forms
from comment.models import Comment
from django.utils.translation import ugettext_lazy as _


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['text', ]

        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control', 'rows': 4,
                                          'placeholder': _("введіть текст коментаря")}),
            }
        labels = {'text': ''}

comment/views.py
from django.shortcuts import render, redirect, get_object_or_404
from comment.forms import CommentForm
from message.models import Message
from django.template.loader import render_to_string
from django.http import JsonResponse
from comment.models import Comment

from django.contrib import messages as messages_django

from webpage.utils import check_user, render_django_message


def save_comment_form(request, form=None, template=None):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():

            # for create comment
            if not form.instance.id:
                data['comment_create'] = 'create'
                massage_id = request.POST.get('id')
                comment_id = request.POST.get('comment-id', '')

                message = get_object_or_404(Message, id=massage_id)

                message_comments_count = len(message.comments()) + 1

                comment = form.save(commit=False)
                comment.content_type = message.get_content_type()
                comment.object_id = message.id
                comment.user = request.user

                if comment_id:
                    instance = Comment.objects.get(id=int(comment_id))
                    comment.parent = instance
                    instance_comments_count = len(instance.children()) + 1

                    data['comment_comments_count'] = instance_comments_count

                comment.save()

                data['message_comments_count'] = message_comments_count

                messages_django.success(request, "Вітаю, Ви створили коментар!", extra_tags='success')

            # for update comment
            elif form.instance.id:
                comment = form.save()

                data['comment_update'] = 'update'

                messages_django.success(request, "Ви змінили коментар!", extra_tags='success')

            data['html_comments'] = render_to_string('partial_comment.html',
                                                     {"comment": comment},
                                                     request=request)
            data['form_is_valid'] = True

        else:
            data['form_is_valid'] = False

    render_django_message(request, data)

    if form:
        data['html_form'] = render_to_string(template,
                                             {'form': form},
                                             request=request)

    return JsonResponse(data)


def comment_create(request):
    if request.user.is_authenticated():
        if request.is_ajax() and request.method == 'POST':
            form = CommentForm(request.POST)
        else:
            form = CommentForm()
    else:
        messages_django.error(request, "Ви не авторизовані на сайті!", extra_tags='error')
        form = None

    return save_comment_form(request, form, 'partial_comment_form.html')


args_update_del = dict(model='comment', error_message="Цей коментар створений не Вами!", func_save=save_comment_form)


@check_user(**args_update_del)
def comment_update(request, comment=None, id=None):

    if request.is_ajax() and request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
    else:
        form = CommentForm(instance=comment)
    return save_comment_form(request, form, 'partial_comment_update.html')


@check_user(**args_update_del)
def comment_delete(request, comment=None, id=None):
    data = dict()

    if request.is_ajax() and request.method == "POST":
        massage_id = request.POST.get('id')

        if comment.has_parent_children():
            parent = comment.parent
            parent_comments_count = parent.children().count() - 1
            data['comment_comments_count'] = parent_comments_count
            data['comment_parent_id'] = parent.id

        else:
            message = get_object_or_404(Message, id=massage_id)
            message_comments_count = len(message.comments()) - 1
            data['message_comments_count'] = message_comments_count

        comment.delete()
        data['form_is_valid'] = True
        messages_django.success(request, "Коментар видалено!", extra_tags='success')

    else:
        context = {'comment': comment}
        data['html_form'] = render_to_string('partial_comment_delete.html',
                                             context, request=request)
    render_django_message(request, data)

    return JsonResponse(data)

comment/templates/comment/partial_comment.html

<div class="comment-{{ comment.id }}">
    <div class="comment" data-id="{{ comment.id }}">
        <p>
            {% if comment.children %}
                <span class="caret caret-toggle"></span>
            {% endif %}

            {{ comment.text }}
        </p>
        <br>
        <p>
            <strong>Створений:</strong> {{ comment.date|timesince }} тому |
            <strong>Кількість коментарів:</strong> <em>{{ comment.children.count }} </em> |
            <strong>Користувач: </strong>

            {% if not comment.user.is_superuser %}

                {{ comment.user.get_full_name }}

            {% else %}

                <strong>Admin</strong>

            {% endif %}

        </p>
    </div>
    <div>
        <p>
            <button type="button" data-comment-id="{{ comment.id }}"
                    data-id="{% if message %}{{ message.id }}{% else %}{{ comment.object_id }}{% endif %}"
                    data-form="{% url "comment:create" %}" class="btn btn-primary js-create-comment"
                    {% if not request.user.is_authenticated %} data-toggle="tooltip"
                    data-original-title="Ви не авторизувалися на сайті!" {# disabled="disabled" #}
                    {% endif %}>
                <span class="glyphicon glyphicon-plus"></span>
                коментувати
            </button>

            <button type="button" data-comment-id="{{ comment.id }}"
                    data-id="{% if message %}{{ message.id }}{% else %}{{ comment.object_id }}{% endif %}"
                    class="btn btn-success btn-sm js-update-comment"
                    data-form="{% url 'comment:update' comment.id %}"
                    {% if request.user !=  comment.user %} data-toggle="tooltip"
                    data-original-title="Даний коментар створене не Вами! " {# disabled="disabled" #}
                    {% endif %}>
                <span class="glyphicon glyphicon-pencil"></span>
                Змінити
            </button>

            <button type="button" data-comment-id="{{ comment.id }}"
                    data-id="{% if message %}{{ message.id }}{% else %}{{ comment.object_id }}{% endif %}"
                    class="btn btn-danger btn-sm js-delete-comment"
                    data-form="{% url 'comment:delete' comment.id %}"
                    {% if request.user !=  comment.user %} data-toggle="tooltip"
                    data-original-title="Дане повідомлення створене не Вами! " {# disabled="disabled" #}
                    {% endif %}>
                <span class="glyphicon glyphicon-trash"></span>
                Видалити
            </button>
        </p>
        <hr/>
    </div>

    <div id="comments-for-comment-id-{{ comment.id }}" class="col-lg-offset-1 col-md-offset-1 col-sm-offset-1 col-xs-offset-1" hidden="hide">

        {% for comment in comment.children %}

            {% include "partial_comment.html" %}

        {% endfor %}

    </div>

</div>


comment/templates/comment/partial_comment_delete.html
<form method="post" action="{% url 'comment:delete' comment.id %}" class="js-comment-delete-form">
    {% csrf_token %}
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Підтвердження видалення коментаря</h4>
    </div>
    <div class="modal-body">
        <p class="lead">Ви впевнені, що хочете видалити коментар створений <strong>{{ comment.date }}.</strong>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрити</button>
        <button type="submit" class="btn btn-danger">Видалити</button>
    </div>
</form>

comment/templates/comment/partial_comment_form.html

<form id="form-comment" class="js-book-comment-form" method="post" action="{% url 'comment:create' %}">
    {% csrf_token %}
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Добавити коментар</h4>
    </div>
    <div class="modal-body">
        {{form.as_p }}
    </div>    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрити</button>
        <button type="submit" class="btn btn-primary">Створити коментар</button>
    </div>
</form>

comment/templates/comment/partial_comment_update.html

<form id="form-comment" class="js-comment-form" method="post" action="{% url 'comment:update' form.instance.id %}">
    {% csrf_token %}
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Змінити коментар</h4>
    </div>
    <div class="modal-body">
        {{form.as_p }}
    </div>    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрити</button>
        <button type="submit" class="btn btn-primary">Змінити</button>
    </div>
</form>

comment/templates/comment/partial_comments_list.html
{% for comment in message.comments %}

    {% include "partial_comment.html" %}

{% endfor %}

