comment/urls.py
from __future__ import unicode_literals

from django.conf.urls import url
from comment.views import (comment_create,
                           comment_update,
                           comment_delete)

app_name = 'comment'

urlpatterns = [
    url(r'^create/$', comment_create, name='create'),
    url(r'^(?P<id>\d+)/update/$', comment_update, name='update'),
    url(r'^(?P<id>\d+)/delete/$', comment_delete, name='delete'),
]

message/urls.py
from __future__ import unicode_literals

from django.conf.urls import url
from message.views import (enter_page,
                           messages_list,
                           message_create,
                           message_update,
                           message_delete)

app_name = 'message'

urlpatterns = [
    url(r'^$', enter_page, name='enter'),
    url(r'^list/$', messages_list, name='list'),
    url(r'^create/$', message_create, name='create'),
    url(r'^update/(?P<id>\d+)/$', message_update, name='update'),
    url(r'^delete/(?P<id>\d+)/$', message_delete, name='delete'),
    ]

webpage/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'social/', include('social.apps.django_app.urls', namespace='social')),

    url(r'^comment/', include('comment.urls', namespace='comment')),
    url(r'^', include('message.urls', namespace='message')),
    ]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}{% load humanize %}
<!DOCTYPE html>
<html>
<head lang="en" xmlns="http://www.w3.org/1999/html">
    <meta charset="UTF-8">

    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>WEB{% block title %}|Home{% endblock %}</title>

    <!-- My css -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">

    <!-- Jquery -->
    <link href="{% static 'css/jquery-ui.css' %}" rel="stylesheet">

    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}" type="image/png">

    <script type="text/javascript" src="{% static 'js/jquery-2.1.4.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-ui.js' %}"></script>

    {% block style %}{% endblock %}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="{% static 'js/html5shiv.min.js' %}"></script>
    <script src="{% static 'js/respond.min.js' %}"></script>
    <![endif]-->

</head>
<body>

<div id="messages_django" class="container">

    {% include 'messages_django.html' %}

</div>

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="jumbotron">

                {% if request.user.is_authenticated %}

                <h3><strong>Користувач:</strong> {% if user.get_full_name %}{{ user.get_full_name }}{% else %}{{ user.username }}{% endif %} (<a href="{% url 'logout' %}?next={{ request.path }}">вийти</a>)</h3>
                {#                        <form method="post" action="{% url 'social:disconnect' 'facebook' %}">#}
                {#                            {% csrf_token %}#}
                {#                            <button type="submit">Вийти з facebook</button>#}
                {#                        </form>#}
                {##}
                {#                        <form method="post" action="{% url 'social:disconnect' 'vk-oauth2' %}">#}
                {#                            {% csrf_token %}#}
                {#                            <button type="submit">Вийти з vk</button>#}
                {#                        </form>#}

                {% else %}

                <h3>Вхід через соціальні мережі</h3>

                <div class="text-center">

                    <a rel="nofollow" class="face" href="{% url 'social:begin' 'facebook' %}" title="Facebook"></a>

                    <a rel="nofollow" class="vkon" href="{% url 'social:begin' 'vk-oauth2'%}" title="ВКонтакте"></a>

                    <a rel="nofollow" class="odn" href="{% url 'social:begin' 'odnoklassniki-oauth2'%}" title="Одноклассники"></a>

                    <a rel="nofollow" class="inl" href="{% url 'social:begin' 'linkedin-oauth2'%}" title="LinkedIn"></a>

                </div>

                {% endif %}

                <h3><a href="{% url 'message:list' %}">Список повідомлень</a></h3>

            </div>
        </div>
    </div>
</div>

{% endblock %}

<script src="{% static 'js/bootstrap.js' %}"></script>
{% block scripts %}{% endblock scripts %}
</body>
</html>

























templates/messages_django.html

{% if message_for_django %}
        {% for message in message_for_django %}
            <div class="has-{{ message.extra_tags }}">
                <label class="control-label">
                    <p><em>{{ message }}</em></p>
                </label>
            </div>
        {% endfor %}
{% endif %}