comment/urls.py
from __future__ import unicode_literals

from django.conf.urls import url
from comment.views import (comment_create,
                           comment_update,
                           comment_delete)

app_name = 'comment'

urlpatterns = [
    url(r'^create/$', comment_create, name='create'),
    url(r'^(?P<id>\d+)/update/$', comment_update, name='update'),
    url(r'^(?P<id>\d+)/delete/$', comment_delete, name='delete'),
]

message/urls.py
from __future__ import unicode_literals

from django.conf.urls import url
from message.views import (enter_page,
                           messages_list,
                           message_create,
                           message_update,
                           message_delete)

app_name = 'message'

urlpatterns = [
    url(r'^$', enter_page, name='enter'),
    url(r'^list/$', messages_list, name='list'),
    url(r'^create/$', message_create, name='create'),
    url(r'^update/(?P<id>\d+)/$', message_update, name='update'),
    url(r'^delete/(?P<id>\d+)/$', message_delete, name='delete'),
    ]

webpage/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'social/', include('social.apps.django_app.urls', namespace='social')),

    url(r'^comment/', include('comment.urls', namespace='comment')),
    url(r'^', include('message.urls', namespace='message')),
    ]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

message/models.py
from django.db import models
from django.conf import settings
from django.contrib.contenttypes.fields import GenericRelation
from comment.models import Comment
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType
from comment.models import Comment


class Message(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="messages", verbose_name=_("Автор повідомлення"),
                             on_delete=models.CASCADE)
    text = models.TextField(verbose_name=_('Текст повідомлення'), max_length=500)
    date = models.DateTimeField(auto_now_add=True, verbose_name=_("Дата створення"))
    update = models.DateTimeField(auto_now=True, verbose_name=_("Дата оновлення"))
    # slug = models.SlugField(verbose_name=_("Ім`я повідомлення транслітом"), blank='', unique='')
    comments = GenericRelation(Comment)

    class Meta:
        db_table = "messages"
        verbose_name = _("Повідомлення")
        verbose_name_plural = _("Повідомлення")

    def __str__(self):
        return 'Клас: {}, id: {}'.format(self.__class__.__name__, self.id)

    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type

    def comments(self):
        qs = Comment.objects.filter_by_instance(self)
        return qs

message/forms.py
from __future__ import unicode_literals

from django import forms
from message.models import Message
from django.utils.translation import ugettext_lazy as _


class MessageForm(forms.ModelForm):

    class Meta:
        model = Message
        fields = ['text', ]

        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control', 'rows': 4,
                                          'placeholder': _("введіть текст повідомлення")}),
            }
        labels = {'text': ''}

message/views.py
from django.shortcuts import render
from message.forms import MessageForm
from message.models import Message
from django.template.loader import render_to_string
from django.http import JsonResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from social.apps.django_app.default.models import UserSocialAuth

from django.contrib import messages as messages_django

from webpage.utils import check_user, render_django_message


def messages_page(request, data, model, count, context=None):
    list = model.objects.all().order_by('-date')
    paginator = Paginator(list, count)
    del_page = data.get('del_page', '')
    if del_page:
        page = del_page
    else:
        page = request.GET.get('page')

    try:
        messages = paginator.page(page)
        # print(articles.page_range)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        messages = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        messages = paginator.page(paginator.num_pages)
    if request.is_ajax():
        data['html_messages'] = render_to_string('partial_messages_list.html',
                                                 {'messages': messages},
                                                 request=request)
        return data
    return context.update({'messages': messages})


def save_message_form(request, form=None, template_form=None):
    data = dict()

    if request.method == 'POST':
        if form.is_valid():
            if form.instance.id:
                message = form.save()
                data['html_message'] = render_to_string('partial_message.html',
                                                        {"message": message},
                                                        request=request)
                messages_django.success(request, "Вітаю, Ваше повідомлення оновлено!", extra_tags='success')
            else:
                message = form.save(commit=False)
                message.user = request.user
                message.save()

                form = MessageForm()
                messages_page(request, data, Message, 2)
                messages_django.success(request, "Вітаю, Ваше повідомлення створено!", extra_tags='success')

            data['form_is_valid'] = True

        else:
            data['form_is_valid'] = False

    render_django_message(request, data)

    if form:
        data['html_form'] = render_to_string(template_form,
                                             {'form': form},
                                             request=request)
    return JsonResponse(data)


def enter_page(request):
    return render(request, 'base.html')


def messages_list(request):
    data = dict()

    user = request.user

    try:
        linkedin_login = user.social_auth.get(provider='linkedin-oauth2')
    except (UserSocialAuth.DoesNotExist, AttributeError):
        linkedin_login = None

    try:
        facebook_login = user.social_auth.get(provider='facebook')
    except (UserSocialAuth.DoesNotExist, AttributeError):
        facebook_login = None

    try:
        vk_login = user.social_auth.get(provider='vk-oauth2')
    except (UserSocialAuth.DoesNotExist, AttributeError):
        vk_login = None

    try:
        odnoklassniki_login = user.social_auth.get(provider='odnoklassniki-oauth2')
    except (UserSocialAuth.DoesNotExist, AttributeError):
        odnoklassniki_login = None

    form = MessageForm()

    context = {
        'title': 'Повідомлення',
        'form': form,
        'linkedin_login': linkedin_login,
        'facebook_login': facebook_login,
        'vk_login': vk_login,
        'odnoklassniki_login': odnoklassniki_login,
        }
    content = messages_page(request, data, Message, 2, context)
    if request.is_ajax():
        return JsonResponse(content)

    return render(request, 'messages.html', context)


def message_create(request):
    form = MessageForm()
    if request.user.is_authenticated():
        if request.is_ajax() and request.method == 'POST':
            form = MessageForm(request.POST)
    else:
        messages_django.error(request, "Ви не авторизовані на сайті!", extra_tags='error')

    return save_message_form(request, form, 'partial_message_form.html')


args_update_del = dict(model='message', error_message="Цей повідомлення створений не Вами!",
                       func_save=save_message_form)


@check_user(**args_update_del)
def message_update(request, message, id=None):

    if request.is_ajax() and request.method == 'POST':
        form = MessageForm(request.POST, instance=message)
    else:
        form = MessageForm(instance=message)

    return save_message_form(request, form, 'partial_message_update.html')


@check_user(**args_update_del)
def message_delete(request, message, id=None):
    data = dict()

    if request.is_ajax() and request.method == 'POST':
        data['html_message_id'] = message.id
        message.delete()

        data['message_delete'] = True

        page = request.GET.get('page')
        data['del_page'] = page

        messages_page(request, data, Message, 2)
        messages_django.success(request, "Ваше повідомлення видалено!", extra_tags='success')
        render_django_message(request, data)

    else:
        context = {'message': message}
        data['html_form'] = render_to_string('partial_message_delete.html',
                                             context, request=request)

    return JsonResponse(data)

message/templates/message/messages.html
{% extends "base.html" %}{% load staticfiles %}{% load humanize %}

{% block title %}|{{ title }}{% endblock %}


{% block style %}

    <link href="{% static 'css/message.css' %}" rel="stylesheet">

{% endblock %}


{% block scripts %}

    <script src="{% static 'js/message.js' %}"></script>
    <script src="{% static 'js/comment.js' %}"></script>

    <script>

        $(function(){
            $('[data-toggle="tooltip"]').tooltip()
        })

    </script>

{% endblock scripts %}


{% block content %}

    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">

            {% if request.user.is_authenticated %}

                <div class="col-lg-8 col-md-8 col-sm-6 col-xs-5">
                    <h3>
                        <a href="{% url 'message:enter' %}" data-toggle="tooltip" data-original-title="Перейти на домашню сторінку" data-placement="right">
                            Привіт, {% if user.get_full_name %}{{ user.get_full_name }}{% else %}{{ user.username }}{% endif %}!
                        </a>
                    </h3>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-7">

                    {% if linkedin_login %}

                        <div class="col-lg-8 col-md-8 col-sm-6 col-xs-6">
                            <a href="{{ linkedin_login.extra_data.public_profile_url }}">
                                <img class="img-rounded" style="float: right;" src="{{ linkedin_login.extra_data.picture_url }}"
                                     data-toggle="tooltip" data-original-title="{{ request.user.get_full_name }}"
                                     data-placement="bottom"/>
                            </a>
                        </div>

                    {% elif facebook_login %}

                        <div class="col-lg-8 col-md-8 col-sm-6 col-xs-6">
                            <a href="{{ facebook_login.extra_data.link }}">
                                <img class="img-rounded" style="float: right;" src="{{ facebook_login.extra_data.picture.data.url }}"
                                     data-toggle="tooltip" data-original-title="{{ request.user.get_full_name }}"
                                     data-placement="bottom"/>
                            </a>
                        </div>

                    {% elif vk_login %}

                        <div class="col-lg-8 col-md-8 col-sm-6 col-xs-6">
                            <a href="http://vk.com/{{ vk_login.extra_data.domain }}">
                                <img class="img-rounded" style="float: right;" src="{{ vk_login.extra_data.photo_50 }}"
                                     data-toggle="tooltip" data-original-title="{{ request.user.get_full_name }}"
                                     data-placement="bottom"/>
                            </a>
                        </div>

                    {% elif odnoklassniki_login %}

                        <div class="col-lg-8 col-md-8 col-sm-6 col-xs-6">
                            <a href="https://ok.ru/profile/{{ odnoklassniki_login.uid}}">
                                <img class="img-rounded" style="float: right;" src="{{ odnoklassniki_login.extra_data.photo }}"
                                     data-toggle="tooltip" data-original-title="{{ request.user.get_full_name }}"
                                     data-placement="bottom"/>
                            </a>
                        </div>

                    {% endif %}

                    <div class="col-lg-4 col-md-4 col-sm-6 col-xs-6">
                        <div class="nav navbar-nav navbar-right">
                            <h4>
                                <strong>
                                    <a href="{% url 'logout' %}?next={{ request.path }}">Вийти</a>
                                </strong>
                            </h4>
                        </div>
                    </div>

                </div>

            {% else %}

                <h3 class="text-center">
                    <a href="{% url 'message:enter' %}" data-toggle="tooltip" data-original-title="Перейти на сторінку авторизації" data-placement="bottom">
                        Щоб залишити повідомлення або коментар зайдіть на сайт!
                    </a>
                </h3>

            {% endif %}

        </div>
    </div>


    <div class="container">
        <div class="row">
            <div id="create-message" class="col-md-5">

                {% include "partial_message_form.html" %}

                <hr/>
            </div>
        </div>

        <div class="row">
            <div id="message-list">

                {% include "partial_messages_list.html" %}

            </div>
        </div>

    </div>

    <!-- THE MODAL WE WILL BE USING -->
    <div id="modal-comment" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
            </div>
        </div>
    </div>

{% endblock %}

message/templates/message/partial_massage_pages.html

{% if messages.has_other_pages %}
    <div id="pagination">
        <ul class="pagination">
            {% if messages.has_previous %}
                <li><a href="?page={{ messages.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&laquo;</a></li>
            {% else %}
                <li class="disabled"><a href="">&laquo;</a></li>
            {% endif %}
            {% for page in messages.paginator.page_range %}
                {% if page == messages.number %}
                    <li class="active"><a href="?page={{ page }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ page }}</a></li>
                {% else %}
                    <li><a href="?page={{ page }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ page }}</a></li>
                {% endif%}
            {% endfor %}
            {% if messages.has_next %}
                <li><a href="?page={{ messages.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">&raquo</a></li>
            {% else %}
                <li class="disabled"><a href="">&raquo</a></li>
            {% endif %}
        </ul>
    </div>

{% endif %}

message/templates/message/partial_message.html

<div id="partial-message-{{ message.id }}">
    <div class="message" data-id="{{ message.id }}">
        <blockquote>
         <p>

            {% if message.comments %}

                <span class="caret caret-toggle"></span>

            {% endif %}

            <strong>({{ message.date|date:"d M Y"}}p.)</strong>

            <em> {{ message.text }}</em>
        </p>
        </blockquote>
    </div>
    <div>
        <p>
            <strong>Кількість коментарів: </strong>
            <em>  {{ message.comments.count }}</em>

            <strong> | Користувач: </strong>
            {% if not message.user.is_superuser %}
                <em>{{ message.user.get_full_name }}</em>
            {% else %}
                <strong><em>Admin</em></strong>
            {% endif %}

            <strong> | Дата створення: </strong>
            <em>  {{ message.date }}</em>
            <strong> | Дата оновлення: </strong>
            <em>  {{ message.update }}</em>
        </p>

        <p>
            <button data-id="{{ message.id }}" data-form="{% url "comment:create" %}"
                    type="button" class="btn btn-toolbar js-create-comment"
                    {% if not request.user.is_authenticated %} data-toggle="tooltip"
                    data-original-title="Ви не авторизувалися на сайті!"
                    {% endif %}>
                <span class="glyphicon glyphicon-plus"></span>
                коментувати
            </button>

            <button data-id="{{ message.id }}" type="button" class="btn btn-warning btn-sm js-update-message"
                    data-url="{% url 'message:update' message.id %}"
                    {% if request.user !=  message.user %} data-toggle="tooltip"
                    data-original-title="Дане повідомлення створене не Вами! "
                    {% endif %}>
                <span class="glyphicon glyphicon-pencil"></span>
                Змінити повідомлення
            </button>

            <button data-id="{{ message.id }}" type="button" class="btn btn-danger btn-sm js-delete-message"
                    data-url="{% url 'message:delete' message.id %}"
                    {% if request.user !=  message.user %} data-toggle="tooltip"
                    data-original-title="Дане повідомлення створене не Вами! "
{#                    disabled="disabled"#}
                    {% endif %}>
                <span class="glyphicon glyphicon-trash"></span>
                Видалити повідомлення
            </button>

        </p>
        <hr/>
    </div>

    <div id="comments-for-message-id-{{ message.id }}" class="col-lg-offset-1 col-md-offset-1 col-sm-offset-1 col-xs-offset-1" hidden="hide">

            {% include "partial_comments_list.html" %}

    </div>

</div>

message/templates/message/partial_message_delete.html
<form method="post" action="{% url 'message:delete' message.id %}" class="js-message-delete-form">
    {% csrf_token %}
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Підтвердження видалення повідомлення</h4>
    </div>
    <div class="modal-body">
        <p class="lead">Ви впевнені, що хочете видалити повідомлення створене <strong>{{ message.date }}.</strong>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрити</button>
        <button type="submit" class="btn btn-danger">Видалити повідомлення</button>
    </div>
</form>

message/templates/message/partial_message_form.html


        <form  id="form-massage" method="POST" action="{% url 'message:create' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p }}
            <input class="btn btn-primary" type="submit" value="відправити"/>
        </form>

message/templates/message/partial_message_update.html


<form id="form-massage" class="js-message-form" data-message-id="{{ form.instance.id }}" method="post" action="{% url 'message:update' form.instance.id %}">
    {% csrf_token %}
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Змінити повідомлення</h4>
    </div>
    <div class="modal-body">
        {{form.as_p }}
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрити</button>
        <button type="submit" class="btn btn-primary">Змінити</button>
    </div>
</form>

message/templates/message/partial_messages_list.html
{% for message in messages %}

    {% include "partial_message.html" %}

{% empty %}

    <div class="col-md-12">

        <h3 class="text-center"><em>Покищо список повідомлень пустий, Ви можете залишити повідомлення першим!</em></h3>

    </div>

{% endfor %}

<div class="row">
    <div id="pages" class="text-center">

        {% include "partial_massage_pages.html" %}

    </div>
</div>

<script>

    $(function(){
        $('[data-toggle="tooltip"]').tooltip()
    })

</script>

